services:
  mysql:
    image: mysql
    ports:
      - "23307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
  postgresql:
    image: postgres
    ports:
      - "25433:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
