name: release
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

permissions:
  contents: write

env:
  GOLANG_CROSS_VERSION: v1.26.0

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
      - name: Run GoReleaser
        run: |
          docker run \
            --rm \
            -e CGO_ENABLED=1 \
            -e GITHUB_TOKEN \
            -v "$GITHUB_WORKSPACE:/src" \
            -w /src \
            ghcr.io/goreleaser/goreleaser-cross:${GOLANG_CROSS_VERSION} \
            release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
